# Generated by Django 3.0.3 on 2020-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=80)),
                ('count', models.IntegerField(max_length=5)),
                ('img_url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('testi', models.TextField(max_length=9999)),
            ],
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
